language: python

python:
  - "3.6"

notifications:
  email: false

install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda config --add channels bioconda
    - travis_retry conda create --yes -n TEST $CONDA --file ./requirements/development.txt
    - source activate TEST
    - pip install brain-isotopic-distribution
    - pip install pymzml

script:
  #- flake8 . --ignore E501 E203
  - python moff_all.py --help

